In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv(".../database/CO2EmissionEstimates.csv", delimiter=',', encoding = "ISO-8859-1", skiprows=1)
data.head(20)

,Region/Country/Area,Unnamed: 1,Year,Series,Value,Footnotes,Source
0,8,Albania,1975,Emissions (thousand metric tons of carbon diox...,"4,524",NaN,"International Energy Agency, IEA World Energy ..."
1,8,Albania,1985,Emissions (thousand metric tons of carbon diox...,"7,145",NaN,"International Energy Agency, IEA World Energy ..."
2,8,Albania,2005,Emissions (thousand metric tons of carbon diox...,"3,980",NaN,"International Energy Agency, IEA World Energy ..."
3,8,Albania,2010,Emissions (thousand metric tons of carbon diox...,"4,074",NaN,"International Energy Agency, IEA World Energy ..."
4,8,Albania,2015,Emissions (thousand metric tons of carbon diox...,"3,975",NaN,"International Energy Agency, IEA World Energy ..."
5,8,Albania,2018,Emissions (thousand metric tons of carbon diox...,"4,525",NaN,"International Energy Agency, IEA World Energy ..."
6,8,Albania,2019,Emissions (thousand metric tons of carbon diox...,"4,200",NaN,"International Energy Agency, IEA World Energy ..."
7,8,Albania,2020,Emissions (thousand metric tons of carbon diox...,"3,512",NaN,"International Energy Agency, IEA World Energy ..."
8,8,Albania,1975,Emissions per capita (metric tons of carbon di...,1.8,NaN,"International Energy Agency, IEA World Energy ..."
9,8,Albania,1985,Emissions per capita (metric tons of carbon di...,2.3,NaN,"International Energy Agency, IEA World Energy ..."
10,8,Albania,2005,Emissions per capita (metric tons of carbon di...,1.3,NaN,"International Energy Agency, IEA World Energy ..."
11,8,Albania,2010,Emissions per capita (metric tons of carbon di...,1.4,NaN,"International Energy Agency, IEA World Energy ..."
12,8,Albania,2015,Emissions per capita (metric tons of carbon di...,1.3,NaN,"International Energy Agency, IEA World Energy ..."
13,8,Albania,2018,Emissions per capita (metric tons of carbon di...,1.5,NaN,"International Energy Agency, IEA World Energy ..."
14,8,Albania,2019,Emissions per capita (metric tons of carbon di...,1.4,NaN,"International Energy Agency, IEA World Energy ..."
15,8,Albania,2020,Emissions per capita (metric tons of carbon di...,1.2,NaN,"International Energy Agency, IEA World Energy ..."
16,12,Algeria,1975,Emissions (thousand metric tons of carbon diox...,"13,691",NaN,"International Energy Agency, IEA World Energy ..."
17,12,Algeria,1985,Emissions (thousand metric tons of carbon diox...,"42,446",NaN,"International Energy Agency, IEA World Energy ..."
18,12,Algeria,2005,Emissions (thousand metric tons of carbon diox...,"78,045",NaN,"International Energy Agency, IEA World Energy ..."
19,12,Algeria,2010,Emissions (thousand metric tons of carbon diox...,"96,452",NaN,"International Energy Agency, IEA World Energy ..."

In [ ]:
data = data.drop(columns=["Footnotes"])
data

,Region/Country/Area,Unnamed: 1,Year,Series,Value,Source
0,8,Albania,1975,Emissions (thousand metric tons of carbon diox...,"4,524","International Energy Agency, IEA World Energy ..."
1,8,Albania,1985,Emissions (thousand metric tons of carbon diox...,"7,145","International Energy Agency, IEA World Energy ..."
2,8,Albania,2005,Emissions (thousand metric tons of carbon diox...,"3,980","International Energy Agency, IEA World Energy ..."
3,8,Albania,2010,Emissions (thousand metric tons of carbon diox...,"4,074","International Energy Agency, IEA World Energy ..."
4,8,Albania,2015,Emissions (thousand metric tons of carbon diox...,"3,975","International Energy Agency, IEA World Energy ..."
...,...,...,...,...,...,...
2259,716,Zimbabwe,2010,Emissions per capita (metric tons of carbon di...,0.7,"International Energy Agency, IEA World Energy ..."
2260,716,Zimbabwe,2015,Emissions per capita (metric tons of carbon di...,0.8,"International Energy Agency, IEA World Energy ..."
2261,716,Zimbabwe,2018,Emissions per capita (metric tons of carbon di...,0.7,"International Energy Agency, IEA World Energy ..."
2262,716,Zimbabwe,2019,Emissions per capita (metric tons of carbon di...,0.7,"International Energy Agency, IEA World Energy ..."
2263,716,Zimbabwe,2020,Emissions per capita (metric tons of carbon di...,0.5,"International Energy Agency, IEA World Energy ..."

In [ ]:
data.dtypes

Region/Country/Area     int64
Unnamed: 1             object
Year                    int64
Series                 object
Value                  object
Source                 object
dtype: object

In [ ]:
data["Value"] = data.Value.replace({',': ''}, regex=True).astype(float)
data

,Region/Country/Area,Unnamed: 1,Year,Series,Value,Source
0,8,Albania,1975,Emissions (thousand metric tons of carbon diox...,4524.0,"International Energy Agency, IEA World Energy ..."
1,8,Albania,1985,Emissions (thousand metric tons of carbon diox...,7145.0,"International Energy Agency, IEA World Energy ..."
2,8,Albania,2005,Emissions (thousand metric tons of carbon diox...,3980.0,"International Energy Agency, IEA World Energy ..."
3,8,Albania,2010,Emissions (thousand metric tons of carbon diox...,4074.0,"International Energy Agency, IEA World Energy ..."
4,8,Albania,2015,Emissions (thousand metric tons of carbon diox...,3975.0,"International Energy Agency, IEA World Energy ..."
...,...,...,...,...,...,...
2259,716,Zimbabwe,2010,Emissions per capita (metric tons of carbon di...,0.7,"International Energy Agency, IEA World Energy ..."
2260,716,Zimbabwe,2015,Emissions per capita (metric tons of carbon di...,0.8,"International Energy Agency, IEA World Energy ..."
2261,716,Zimbabwe,2018,Emissions per capita (metric tons of carbon di...,0.7,"International Energy Agency, IEA World Energy ..."
2262,716,Zimbabwe,2019,Emissions per capita (metric tons of carbon di...,0.7,"International Energy Agency, IEA World Energy ..."
2263,716,Zimbabwe,2020,Emissions per capita (metric tons of carbon di...,0.5,"International Energy Agency, IEA World Energy ..."

In [ ]:
data = data.rename(columns={"Region/Country/Area": "Area code", "Unnamed: 1": "Area"})
data

,Country code,Country,Year,Series,Value,Source
0,8,Albania,1975,Emissions (thousand metric tons of carbon diox...,4524.0,"International Energy Agency, IEA World Energy ..."
1,8,Albania,1985,Emissions (thousand metric tons of carbon diox...,7145.0,"International Energy Agency, IEA World Energy ..."
2,8,Albania,2005,Emissions (thousand metric tons of carbon diox...,3980.0,"International Energy Agency, IEA World Energy ..."
3,8,Albania,2010,Emissions (thousand metric tons of carbon diox...,4074.0,"International Energy Agency, IEA World Energy ..."
4,8,Albania,2015,Emissions (thousand metric tons of carbon diox...,3975.0,"International Energy Agency, IEA World Energy ..."
...,...,...,...,...,...,...
2259,716,Zimbabwe,2010,Emissions per capita (metric tons of carbon di...,0.7,"International Energy Agency, IEA World Energy ..."
2260,716,Zimbabwe,2015,Emissions per capita (metric tons of carbon di...,0.8,"International Energy Agency, IEA World Energy ..."
2261,716,Zimbabwe,2018,Emissions per capita (metric tons of carbon di...,0.7,"International Energy Agency, IEA World Energy ..."
2262,716,Zimbabwe,2019,Emissions per capita (metric tons of carbon di...,0.7,"International Energy Agency, IEA World Energy ..."
2263,716,Zimbabwe,2020,Emissions per capita (metric tons of carbon di...,0.5,"International Energy Agency, IEA World Energy ..."

In [ ]:
data.to_csv(".../database/fixed/CO2EmissionEstimates.csv", index=False)