In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("../database/ExchangeRates.csv", delimiter=',', encoding = "ISO-8859-1", skiprows=1)
data

,Region/Country/Area,Unnamed: 1,Year,Series,National currency,National currency footnote,Value,Footnotes,Source
0,4,Afghanistan,1995,Exchange rates: end of period (national curren...,Afghani (AFN),NaN,47.5,NaN,"International Monetary Fund (IMF), Washington,..."
1,4,Afghanistan,2005,Exchange rates: end of period (national curren...,Afghani (AFN),NaN,50.4,NaN,"International Monetary Fund (IMF), Washington,..."
2,4,Afghanistan,2010,Exchange rates: end of period (national curren...,Afghani (AFN),NaN,45.3,NaN,"International Monetary Fund (IMF), Washington,..."
3,4,Afghanistan,2015,Exchange rates: end of period (national curren...,Afghani (AFN),NaN,68.1,NaN,"International Monetary Fund (IMF), Washington,..."
4,4,Afghanistan,2019,Exchange rates: end of period (national curren...,Afghani (AFN),NaN,78.4,NaN,"International Monetary Fund (IMF), Washington,..."
...,...,...,...,...,...,...,...,...,...
3547,98,Euro Area,2015,Exchange rates: period average (national curre...,NaN,NaN,0.9,NaN,"International Monetary Fund (IMF), Washington,..."
3548,98,Euro Area,2019,Exchange rates: period average (national curre...,NaN,NaN,0.9,NaN,"International Monetary Fund (IMF), Washington,..."
3549,98,Euro Area,2020,Exchange rates: period average (national curre...,NaN,NaN,0.9,NaN,"International Monetary Fund (IMF), Washington,..."
3550,98,Euro Area,2021,Exchange rates: period average (national curre...,NaN,NaN,0.8,NaN,"International Monetary Fund (IMF), Washington,..."
3551,98,Euro Area,2022,Exchange rates: period average (national curre...,NaN,NaN,0.9,NaN,"International Monetary Fund (IMF), Washington,..."

In [3]:
data = data.drop(columns=["Footnotes", "National currency footnote"])
data

,Region/Country/Area,Unnamed: 1,Year,Series,National currency,Value,Source
0,4,Afghanistan,1995,Exchange rates: end of period (national curren...,Afghani (AFN),47.5,"International Monetary Fund (IMF), Washington,..."
1,4,Afghanistan,2005,Exchange rates: end of period (national curren...,Afghani (AFN),50.4,"International Monetary Fund (IMF), Washington,..."
2,4,Afghanistan,2010,Exchange rates: end of period (national curren...,Afghani (AFN),45.3,"International Monetary Fund (IMF), Washington,..."
3,4,Afghanistan,2015,Exchange rates: end of period (national curren...,Afghani (AFN),68.1,"International Monetary Fund (IMF), Washington,..."
4,4,Afghanistan,2019,Exchange rates: end of period (national curren...,Afghani (AFN),78.4,"International Monetary Fund (IMF), Washington,..."
...,...,...,...,...,...,...,...
3547,98,Euro Area,2015,Exchange rates: period average (national curre...,NaN,0.9,"International Monetary Fund (IMF), Washington,..."
3548,98,Euro Area,2019,Exchange rates: period average (national curre...,NaN,0.9,"International Monetary Fund (IMF), Washington,..."
3549,98,Euro Area,2020,Exchange rates: period average (national curre...,NaN,0.9,"International Monetary Fund (IMF), Washington,..."
3550,98,Euro Area,2021,Exchange rates: period average (national curre...,NaN,0.8,"International Monetary Fund (IMF), Washington,..."
3551,98,Euro Area,2022,Exchange rates: period average (national curre...,NaN,0.9,"International Monetary Fund (IMF), Washington,..."

In [4]:
data.dtypes

Region/Country/Area     int64
Unnamed: 1             object
Year                    int64
Series                 object
National currency      object
Value                  object
Source                 object
dtype: object

In [ ]:
data["Value"] = data.Value.replace({',': ''}, regex=True).astype(float)
data

,Region/Country/Area,Unnamed: 1,Year,Series,National currency,Value,Source
0,4,Afghanistan,1995,Exchange rates: end of period (national curren...,Afghani (AFN),47.5,"International Monetary Fund (IMF), Washington,..."
1,4,Afghanistan,2005,Exchange rates: end of period (national curren...,Afghani (AFN),50.4,"International Monetary Fund (IMF), Washington,..."
2,4,Afghanistan,2010,Exchange rates: end of period (national curren...,Afghani (AFN),45.3,"International Monetary Fund (IMF), Washington,..."
3,4,Afghanistan,2015,Exchange rates: end of period (national curren...,Afghani (AFN),68.1,"International Monetary Fund (IMF), Washington,..."
4,4,Afghanistan,2019,Exchange rates: end of period (national curren...,Afghani (AFN),78.4,"International Monetary Fund (IMF), Washington,..."
...,...,...,...,...,...,...,...
3547,98,Euro Area,2015,Exchange rates: period average (national curre...,NaN,0.9,"International Monetary Fund (IMF), Washington,..."
3548,98,Euro Area,2019,Exchange rates: period average (national curre...,NaN,0.9,"International Monetary Fund (IMF), Washington,..."
3549,98,Euro Area,2020,Exchange rates: period average (national curre...,NaN,0.9,"International Monetary Fund (IMF), Washington,..."
3550,98,Euro Area,2021,Exchange rates: period average (national curre...,NaN,0.8,"International Monetary Fund (IMF), Washington,..."
3551,98,Euro Area,2022,Exchange rates: period average (national curre...,NaN,0.9,"International Monetary Fund (IMF), Washington,..."

In [7]:
data = data.rename(columns={"Region/Country/Area": "Area code", "Unnamed: 1": "Area"})
data

,Area code,Area,Year,Series,National currency,Value,Source
0,4,Afghanistan,1995,Exchange rates: end of period (national curren...,Afghani (AFN),47.5,"International Monetary Fund (IMF), Washington,..."
1,4,Afghanistan,2005,Exchange rates: end of period (national curren...,Afghani (AFN),50.4,"International Monetary Fund (IMF), Washington,..."
2,4,Afghanistan,2010,Exchange rates: end of period (national curren...,Afghani (AFN),45.3,"International Monetary Fund (IMF), Washington,..."
3,4,Afghanistan,2015,Exchange rates: end of period (national curren...,Afghani (AFN),68.1,"International Monetary Fund (IMF), Washington,..."
4,4,Afghanistan,2019,Exchange rates: end of period (national curren...,Afghani (AFN),78.4,"International Monetary Fund (IMF), Washington,..."
...,...,...,...,...,...,...,...
3547,98,Euro Area,2015,Exchange rates: period average (national curre...,NaN,0.9,"International Monetary Fund (IMF), Washington,..."
3548,98,Euro Area,2019,Exchange rates: period average (national curre...,NaN,0.9,"International Monetary Fund (IMF), Washington,..."
3549,98,Euro Area,2020,Exchange rates: period average (national curre...,NaN,0.9,"International Monetary Fund (IMF), Washington,..."
3550,98,Euro Area,2021,Exchange rates: period average (national curre...,NaN,0.8,"International Monetary Fund (IMF), Washington,..."
3551,98,Euro Area,2022,Exchange rates: period average (national curre...,NaN,0.9,"International Monetary Fund (IMF), Washington,..."

In [8]:
data.to_csv("../database/fixed/ExchangeRates.csv", index=False)